---
# Site settings 配置站点
title: 'WongHoyu's blog'
description: '黄浩宇个人博客,可能会有个人生活,工作中学习到的知识'
keywords: 'Life,Knowledge'
url: https://www.wonghoyu.com'
---

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  首页: '/'
  标签: '/tags.html'
  时间线: '/timeline.html'
  关于博主: '/about.html'
  友情链接: '/friendLink.html'

# 博主
author: true
name: 'Wong Hoyu'
#NickName: 'your awesome nickname'
webtitle: 'https://github.com/WongHoyu'
bio: 'your awesome bio'
about: true
aboutyou: '一个还没有秃头的菜鸟程序员'
portraits: '/assets/profile.jpeg' # your portraits image file path

# SNS
SNS: false
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:abc@gmail.com'
  weixin: '' # 你的微信二维码存放的地址
  qq: '' # 你的qq二维码存放的地址 or http://wpa.qq.com/msgrd?v=3&uin='你的QQ号'&site=qq&menu=yes
  github: ''
  Codepen: ''
  weibo: ''
  instagram: ''
  Twitter: ''
  Dribbble: ''
  Facebook: ''
  Google: ''
  zhihu: ''
  juejin: ''
  twitch: ''

# 分页
paginate: 5
paginatepath: ['page:num']

# since
footer:
  since: 2019

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'default'

# 友情链接
friends:
  jekyll: 'https://www.jekyll.com.cn/'

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: true
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: true
baidu-url: '<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?37917361bb28acdab4f8d3f6146ad92e";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
'
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: false
google-ID: ''

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
